### PR TITLE
Changes to build dependencies

### PR DESCRIPTION
**Pull request by burnsfisher**
Adding DCT power to downlink

### CODE REVIEW

**Comment by ac2cz** [comment]
Can I ignore this?  It seems to contain only one commit and that is  commit that I made.  I changed something in the eclipse build script.  So it should already be in the code.

**Comment by burnsfisher** [comment]
I'm not sure I know what is going on.  It should have added two fields to common, which would have been reflected in WOD, Min, Max, and RT.  Did I mess something up?  I'm not 100% sure how branches work in github.  Is this somehow in master rather than 1.09?

**Comment by ac2cz** [comment]
There were two pull requests.  This one and another one here #651.  I merged the other one in fine.  Is that the one you are referring too?  Did it automatically create two pull requests because of the conflict?  Or because this commit was made by me?

I think we can ignore that as long as your changes were in the other pull request - which had two commits from you.

**Comment by burnsfisher** [comment]
No, the other one I added a week or so ago.  It was a larger change,
moving some stuff from common to common2 and thus changing some payload
sizes (but not the full frames).  This one replaces a couple of pad bytes
with DCT1RFPower and DCT2RfPower (or some similar name).  As I say, I might
well have messed up!

**Comment by burnsfisher** [comment]
If we can't figure it out, I'll check the branches on my local git repo.
It's possible I did not push the 1.09 branch to github or something like
that.  (Not today probably)

**Pull request closed without merging**
