### PR TITLE
1.12 -  A couple of frame bugfixes

### PR DESCRIPTION
**Pull request by burnsfisher**
Wanted to fix this before giving you an RF recording

### CODE REVIEW

**Comment by ac2cz** [comment]
This pull request is against my Master branch from your 1.12.  I don't think that is what you intended.  I changed the base to be my 1.12 branch and it tells me there is nothing to Merge.  Do you want to close this out and send another pull request?

**Comment by burnsfisher** [comment]
Oh, foo.  Sorry I messed that up.  but I think it is all set because as I
said in the other mail, I think that I actually got it all checked in
directly.

**Comment by ac2cz** [comment]
I'm closing this one because it resulted in no changes.  Do you think this could be part of the issue?  Is it one of the commits where you are ahead?

**Comment by burnsfisher** [comment]
I don't think this one is a problem.  But who knows?  :-)

**Pull request closed without merging**
