### PR TITLE
Added blank EXIF header to JPG "template" file

### PR DESCRIPTION
**Pull request by mistermatt2u**
Added a blank EXIF header to both the jpeg_header.jpg and jpeg_header_low_res.jpg files. This was done using the Linux 'exif -c' command. This should permit programatic adding of EXIF data (ie. sat overhead location) during the crafting of each .jpg file that is created by FoxTelem.

### CODE REVIEW

**Comment by mistermatt2u** [comment]
@ac2cz Chris, per our e-mail conversations on the FITS list, I've added the EXIF bytes to the two files that are used by FoxTelem to generate the pictures for the AMSAT website. Perhaps you can test these changes by re-generating JPGs from a previous pass. Not sure how you can do that on the server. But the resulting image should be exactly the same, except that now there is valid (blank) EXIF data.

If this works ok, then we can proceed with adding some EXIF parsing code in the webpage generation area. After that of course would be trying to inject useful EXIF data into the JPG, such as the sat's overhead location at the time the picture was taken.

**Comment by ac2cz** [comment]
Ok, thanks for this.  I have merged it into a new branch called server_0.29.  I am going to use that branch to track a couple of changes that I want to make to the server.  For now it will just have the code for this EXIF change.  The branch is based on the current development branch for 1.06, which is stable and about to be released as a patch for FoxTelem.

**Comment by ac2cz** [comment]
To test this we ideally want a recording of a previous pass.  I have some test data from before launch, but it would be better to use the real image data.

Are you able to build the server jar file from Eclipse?  Or run it directly from Eclipse?  I can talk you through how to do it if you have not done that already.  If you can, then I will write up a procedure to run the test server with a local copy of FoxTelem.

**Comment by mistermatt2u** [comment]
I should be able to get a test environment going. I have not tried to build the foxtelem server or client. I have a Linux VM that I will probably try to use for the server.

I wonder if SATNOGS captured one of the image transmissions. I will check their db. That would be a good way to get a recorded transmission.

On March 10, 2018 10:13:24 PM GMT+07:00, Chris Thompson <notifications@github.com> wrote:
>To test this we ideally want a recording of a previous pass.  I have
>some test data from before launch, but it would be better to use the
>real image data.
>
>Are you able to build the server jar file from Eclipse?  Or run it
>directly from Eclipse?  I can talk you through how to do it if you have
>not done that already.  If you can, then I will write up a procedure to
>run the test server with a local copy of FoxTelem. 
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ac2cz/FoxTelem/pull/464#issuecomment-372037147

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
